GET http://localhost:5101/blogs

###
GET http://localhost:5101/blogs/1

###
POST http://localhost:5101/blogs
Content-Type: application/json

{
    "title": "My Fourth Blog Post",
    "content": "This is the content of my fourth blog post.",
    "category": "Gaming",
    "tags": ["Nintendo", "Mario"]
}

###
PUT http://localhost:5101/blogs/1
Content-Type: application/json

{
    "id": 1,
    "title": "My First Blog Post",
    "content": "I updated the content of my first post.",
    "category": "Technology",
    "tags": [
      "Tech",
      "Programming"
    ]
}

### 
DELETE http://localhost:5101/blogs/1